### ISSUE TITLE
panic on android

### ISSUE THREAD

**Issue by gaillard** [DataDog/datadog-trace-agent#445]
Similar to https://github.com/DataDog/gohai/issues/57 i'm trying to build and run on an android box with `GOOS=android GOARCH=arm GOARM=7 CGO_ENABLED=1 go generate ./info` and `GOOS=android GOARCH=arm GOARM=7 CGO_ENABLED=1 go build -o trace-agent ./cmd/trace-agent`

But when running on the box, it works and I see profile's in datadog site, but then panics.

Couple other questions I could find in the repos/site:
Does the trace agent have to be manually run along side the regular agent? Or does the regular agent start it if located in a certain place?
Does the trace agent depend on the regular agent for functionality or upload to datadog on it's own?
I don't see a "service" in the datadog site created, only point in time profile's?

```
2018-06-26 23:23:13 DEBUG (sampler.go:105) - *sampler.ScoreEngine: inTPS: 0.027939, outTPS: 0.027939, maxTPS: 10.000000, offset: 1.000000, slope: 3.000000, cardinality: 1
seelog internal error: mkdir /var: read-only file system
2018-06-26 23:23:13 DEBUG (trace_writer.go:124) - Flushing current traces
seelog internal error: mkdir /var: read-only file system
2018-06-26 23:23:13 DEBUG (stats_writer.go:107) - going to flush 3 entries in 1 stat buckets in 1 payloads
seelog internal error: mkdir /var: read-only file system
2018-06-26 23:23:13 ERROR (logonpanic.go:38) - Unexpected panic: runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
github.com/DataDog/datadog-trace-agent/watchdog.LogOnPanic()
	/go/src/github.com/DataDog/datadog-trace-agent/watchdog/logonpanic.go:29 +0x84
panic(0xab8690d8, 0xabab6688)
	/usr/local/go/src/runtime/panic.go:505 +0x218
sync/atomic.addUint64(0xbc742264, 0x1, 0x0, 0x3, 0x3)
	/usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x4c
github.com/DataDog/datadog-trace-agent/writer.(*StatsWriter).handleStats(0xbc742240, 0xbc7f43e0, 0x1, 0x1)
	/go/src/github.com/DataDog/datadog-trace-agent/writer/stats_writer.go:114 +0x1a4
github.com/DataDog/datadog-trace-agent/writer.(*StatsWriter).Run(0xbc742240)
	/go/src/github.com/DataDog/datadog-trace-agent/writer/stats_writer.go:82 +0xd4
github.com/DataDog/datadog-trace-agent/writer.(*StatsWriter).Start.func1(0xbc742240)
	/go/src/github.com/DataDog/datadog-trace-agent/writer/stats_writer.go:62 +0x3c
created by github.com/DataDog/datadog-trace-agent/writer.(*StatsWriter).Start
	/go/src/github.com/DataDog/datadog-trace-agent/writer/stats_writer.go:60 +0x40
```

**Comment by gbbr** [comment]
Thanks for reporting this. I'm hoping to be able to investigate this error somehow and provide you with more information soon. 

In the meantime, it might help to get answers to the following questions:
* Which version of the trace agent are you running? Would you be able to try out our [latest](https://github.com/DataDog/datadog-trace-agent/releases/latest) and see if the problem is still there?
* There seems to be an error writing to `/var` on your box. Can you set the log file path to something writable? If you use `.conf` or `.ini` files, set the `log_file` setting in the `[trace.config]` section. If you use `yaml`, set the `log_file` option in the `apm_config` group. Perhaps better logging might provide more information.

To answer your questions:

> Does the trace agent have to be manually run along side the regular agent?

On Linux and Windows the trace agent is shipped together with the main agent. On other platforms it's not. So you have to run it separately, just as you did.
> Does the trace agent depend on the regular agent for functionality or upload to datadog on it's own?

The trace agent is capable of running on its own as a stand alone service. It does not necessarily require the Datadog agent.

**Comment by gaillard** [comment]
Hi thanks !

I was running the latest commit from master (5c6958a102824d7bf8ce76e38fe43099adcf3d9b).
I'll change the log config and post back here. (I had set disable_file_logging to yes to avoid the same error in the regular agent)

**Comment by gaillard** [comment]
@gbbr putting log_file into the apm_config section did not have an effect, no file written.

**Comment by burningion** [comment]
Hey @gaillard!

I just built the Agent (along with the Trace Agent) natively on ARMv8. I used the source for both repositories, and ran the trace-agent manually. 

I'd be happy to help you with your build on ARMv7, if you could provide a bit more detail about your platform. Is it  ARMv7 specific? Anything I can buy off the shelf to test locally?

Feel free to reach out to me on the public Datadog Slack channel, I'm Kirk Kaiser there, and my DMs should be open.

- Kirk
